### ISSUE TITLE
Create a link to this repo on open-rpc.org

### ISSUE THREAD

**Issue by BelfordZ** [avto-dev/open-rpc-docs-builder-docker#1]
Hey there,

Firstly, nice work on this project. Great to see more OpenRPC tooling.

I just wanted to extend to you the invitation to add a link to this project on the open-rpc website. heres a link to the repo: https://github.com/open-rpc/open-rpc

Cheers!

**Comment by jetexe** [comment]
Thank for your invitation!
We have created an appropriate PR!

**Comment by jetexe** [comment]
PR Merged
